# Pandas basics

In [2]:
# popular library for data manipulation and analysis

In [3]:
import pandas as pd

In [5]:
 # create a series of data :
A = pd.Series([2,3,4,5], index = ['a','b','c','d'])

In [6]:
# present the values :
A.values

array([2, 3, 4, 5], dtype=int64)

In [9]:
# type :
print(type(A))
print(type(A.values))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [10]:
# present the index values :
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
# we can work like we are working in dictionary :
A['a']

2

In [12]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [25]:
# another way or making a series object :
grades_dict = {'A':4, 'A-':3.5, 'B':3, 'B-':2.5}
marks_dict = {'A':85, 'A-':80, 'B':75, 'B-':70}

In [26]:
grades = pd.Series(grades_dict)
marks = pd.Series(marks_dict)

In [29]:
grades.values

array([4. , 3.5, 3. , 2.5])

In [30]:
marks.index

Index(['A', 'A-', 'B', 'B-'], dtype='object')

# DataFrames

In [31]:
# we want to make df from marks and grades:
D = pd.DataFrame({'Marks':marks, 'Grades':grades})

In [36]:
# and we can present it :
D

Marks  Grades
A      85     4.0
A-     80     3.5
B      75     3.0
B-     70     2.5

In [33]:
# we can akso transpose it :
D.T

A    A-     B    B-
Marks   85.0  80.0  75.0  70.0
Grades   4.0   3.5   3.0   2.5

In [37]:
# if we access the values in D :
D.values

array([[85. ,  4. ],
       [80. ,  3.5],
       [75. ,  3. ],
       [70. ,  2.5]])

In [40]:
# if we want to access a spicific value:
D.values[0,1]

4.0

In [41]:
# we want to add another column to D :
D['ScalesMarks'] = 100*(D['Marks']/90)

In [42]:
D

Marks  Grades  ScalesMarks
A      85     4.0    94.444444
A-     80     3.5    88.888889
B      75     3.0    83.333333
B-     70     2.5    77.777778

In [43]:
# if we want to delete the column :
del D['ScalesMarks']

In [44]:
D

Marks  Grades
A      85     4.0
A-     80     3.5
B      75     3.0
B-     70     2.5

In [46]:
# making a new df depending on a curent df :
G = D[D['Marks']>70]

In [47]:
G

Marks  Grades
A      85     4.0
A-     80     3.5
B      75     3.0

In [55]:
# make df from lists :
x = [1,2,3,4]
y = [100,200,300,400]
z = pd.DataFrame(list(zip(x,y)), columns = ['x','y'])

In [56]:
z

x    y
0  1  100
1  2  200
2  3  300
3  4  400

In [59]:
# make df from one list :
h = pd.DataFrame(x, columns=['x'])

In [60]:
h

x
0  1
1  2
2  3
3  4

# NaN

In [61]:
# not a numner ( missing values):

In [65]:
C = pd.DataFrame([{'a':1, 'b':4},{'b':-3, 'c':9}])

In [67]:
#as we can see a has one value '1', c has one value '9'
#but b has two values : 4,-3 so we will have NaN values
C

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [68]:
# we can fill the null values with this function :
C.fillna(0)

a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

In [69]:
# another function that drops the null values:
A.dropna?

# indexing

In [70]:
# if we have [1,3,5] so when we do data[1:3] we dont know
# if we are referring to the actual vlaues of their places in the data
E = pd.Series(['a','b','c'],index=[1,3,5])

In [71]:
E

1    a
3    b
5    c
dtype: object

In [75]:
E[1:3]

3    b
5    c
dtype: object

In [77]:
# LOC : it means to use explicit indicies (actual values):
E.loc[1:3]

1    a
3    b
dtype: object

In [78]:
# iLOC : it means to use implicit indicies (values's places):
E.iloc[1:3]

3    b
5    c
dtype: object

In [79]:
# we have 'G' marks and grades df :
G

Marks  Grades
A      85     4.0
A-     80     3.5
B      75     3.0

In [83]:
# we want to access the third row
G.iloc[2,:]

Marks     75.0
Grades     3.0
Name: B, dtype: float64

In [84]:
#  we can also change the values : 
# reverse all the rows :
D.iloc[::-1,:]

Marks  Grades
B-     70     2.5
B      75     3.0
A-     80     3.5
A      85     4.0

# CSV Files

In [85]:
 # we need to import some libraris :
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [86]:
# read the data :
df = pd.read_csv('C:\Datasets\covid_19_data.csv')

In [87]:
# head fo the df :
df.head()

Province/State Country/Region      Lat      Long     Date  Confirmed  \
0            NaN       Thailand  15.0000  101.0000  1/22/20          2   
1            NaN          Japan  36.0000  138.0000  1/22/20          2   
2            NaN      Singapore   1.2833  103.8333  1/22/20          0   
3            NaN          Nepal  28.1667   84.2500  1/22/20          0   
4            NaN       Malaysia   2.5000  112.5000  1/22/20          0   

   Deaths  Recovered  
0       0          0  
1       0          0  
2       0          0  
3       0          0  
4       0          0

In [88]:
# or we can show the first 10 records :
df.head(10)

Province/State Country/Region      Lat      Long     Date  Confirmed  \
0               NaN       Thailand  15.0000  101.0000  1/22/20          2   
1               NaN          Japan  36.0000  138.0000  1/22/20          2   
2               NaN      Singapore   1.2833  103.8333  1/22/20          0   
3               NaN          Nepal  28.1667   84.2500  1/22/20          0   
4               NaN       Malaysia   2.5000  112.5000  1/22/20          0   
5  British Columbia         Canada  49.2827 -123.1207  1/22/20          0   
6   New South Wales      Australia -33.8688  151.2093  1/22/20          0   
7          Victoria      Australia -37.8136  144.9631  1/22/20          0   
8        Queensland      Australia -28.0167  153.4000  1/22/20          0   
9               NaN       Cambodia  11.5500  104.9167  1/22/20          0   

   Deaths  Recovered  
0       0          0  
1       0          0  
2       0          0  
3       0          0  
4       0          0  
5       0          0  
6       0          0  
7       0          0  
8       0          0  
9       0          0

In [90]:
# we want to delete lat,long volumns :
# axis = 1 : do that thing with columns
# inplace=True : reflex the changes on this df
df.drop(['Lat','Long'],axis=1, inplace=True)

# Manipulate Data

In [91]:
df.head()

Province/State Country/Region     Date  Confirmed  Deaths  Recovered
0            NaN       Thailand  1/22/20          2       0          0
1            NaN          Japan  1/22/20          2       0          0
2            NaN      Singapore  1/22/20          0       0          0
3            NaN          Nepal  1/22/20          0       0          0
4            NaN       Malaysia  1/22/20          0       0          0

In [92]:
# rename the columns :
df.rename(columns= {'Province/State':'Province', 'Country/Region':'Country'},inplace = True)

In [93]:
df.head()

Province    Country     Date  Confirmed  Deaths  Recovered
0      NaN   Thailand  1/22/20          2       0          0
1      NaN      Japan  1/22/20          2       0          0
2      NaN  Singapore  1/22/20          0       0          0
3      NaN      Nepal  1/22/20          0       0          0
4      NaN   Malaysia  1/22/20          0       0          0

In [94]:
# this date format is not pandas date format so we must change it ;
df['Date'] = pd.to_datetime(df['Date'])

In [96]:
df.head()

Province    Country       Date  Confirmed  Deaths  Recovered
0      NaN   Thailand 2020-01-22          2       0          0
1      NaN      Japan 2020-01-22          2       0          0
2      NaN  Singapore 2020-01-22          0       0          0
3      NaN      Nepal 2020-01-22          0       0          0
4      NaN   Malaysia 2020-01-22          0       0          0

In [97]:
# we can describe the statistics of the data :
df.describe()

Confirmed        Deaths     Recovered
count  17460.000000  17460.000000  17460.000000
mean     278.236655      9.592726    102.221879
std     3278.574938    146.222382   1767.485397
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000
75%        8.000000      0.000000      0.000000
max    67800.000000   4825.000000  58946.000000

In [98]:
# or information about the data :
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17460 entries, 0 to 17459
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   Province   8040 non-null   object        
 1   Country    17460 non-null  object        
 2   Date       17460 non-null  datetime64[ns]
 3   Confirmed  17460 non-null  int64         
 4   Deaths     17460 non-null  int64         
 5   Recovered  17460 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 818.6+ KB


In [101]:
# we saw that we have empty values on 'province' column
# so we want to fill the missing values with the word 'NA' :
df = df.fillna('NA')

In [102]:
# there is no more null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17460 entries, 0 to 17459
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   Province   17460 non-null  object        
 1   Country    17460 non-null  object        
 2   Date       17460 non-null  datetime64[ns]
 3   Confirmed  17460 non-null  int64         
 4   Deaths     17460 non-null  int64         
 5   Recovered  17460 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 818.6+ KB


# Data retrieval

In [106]:
# GROUP BY :
# we want to group the records by the country (like SQL):
# the sum will sum all the values:
df2 = df.groupby('Country')[['Country','Confirmed','Deaths','Recovered']].sum().reset_index()

In [107]:
df2

Country  Confirmed  Deaths  Recovered
0    Afghanistan        209       0          6
1        Albania        535      15          2
2        Algeria        790      60        172
3        Andorra        310       0          9
4         Angola          3       0          0
..           ...        ...     ...        ...
161   Uzbekistan        131       0          0
162    Venezuela        252       0          0
163      Vietnam       1326       0        551
164       Zambia          8       0          0
165     Zimbabwe          4       0          0

[166 rows x 4 columns]

In [110]:
# group by country then date
df3 = df.groupby(['Country','Date'])[['Country','Date','Confirmed','Deaths','Recovered']].sum().reset_index()

In [111]:
df3

Country       Date  Confirmed  Deaths  Recovered
0     Afghanistan 2020-01-22          0       0          0
1     Afghanistan 2020-01-23          0       0          0
2     Afghanistan 2020-01-24          0       0          0
3     Afghanistan 2020-01-25          0       0          0
4     Afghanistan 2020-01-26          0       0          0
...           ...        ...        ...     ...        ...
9955     Zimbabwe 2020-03-17          0       0          0
9956     Zimbabwe 2020-03-18          0       0          0
9957     Zimbabwe 2020-03-19          0       0          0
9958     Zimbabwe 2020-03-20          1       0          0
9959     Zimbabwe 2020-03-21          3       0          0

[9960 rows x 5 columns]

In [113]:
# we want all the records with confirmed >100:
df4 = df3[df3['Confirmed']>100]

In [114]:
df4

Country       Date  Confirmed  Deaths  Recovered
179          Algeria 2020-03-21        139      15         32
418        Argentina 2020-03-20        128       3          3
419        Argentina 2020-03-21        158       4          3
477          Armenia 2020-03-19        115       0          1
478          Armenia 2020-03-20        136       0          1
...              ...        ...        ...     ...        ...
9596  United Kingdom 2020-03-18       2642      72         67
9597  United Kingdom 2020-03-19       2716     138         67
9598  United Kingdom 2020-03-20       4014     178         67
9599  United Kingdom 2020-03-21       5067     234         67
9659         Uruguay 2020-03-21        110       0          0

[755 rows x 5 columns]